#ifndef VOXBOTCREATOR_GLOBAL_H
#define VOXBOTCREATOR_GLOBAL_H

#if defined(VOXBOTCREATOR_LIBRARY)
#  define VOXBOTCREATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VOXBOTCREATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VOXBOTCREATOR_GLOBAL_H
